### PR TITLE
Update zh-cn Translation (Continuation of #2013)

### PR DESCRIPTION
**Pull request by aquila-zyy**
This branch is partially based on the work of #2013, but with entries that were added after that pr also translated. Also fixed a lot of mistakes / gibberish (possibly machine translation).

The translation should be complete with both the book and items that are obtainable in-game translated. Much of the translations were borrowed from the 1.12.2 version (notably the advancement texts) for the sake of consistency.

### CODE REVIEW

**Comment by eerussianguy** [comment]
Would this PR completely replace the other PR? As in if we merge, this should the other be closed?

please also let us know when you consider it ready to be merged

**Comment by aquila-zyy** [comment]
Yes, this completely replaces the other one.

I noticed that Alc is refactoring some translation keys on #2086, I think I'll wait till that one is settled, so that I can make necessary modifications accordingly before we merge everything in one go.

**Comment by eerussianguy** [comment]
Please update this, we have changed a lot of our translation keys to be more friendly for translators

**Comment by aquila-zyy** [comment]
This branch is up-to-date with the latest translation keys. If no further changes would be made, this branch will be ready to be merged.

A few things to be noted:
1. Currently the key for filled ceramic jugs is missing. I've made an educated guess, and added the key back manually only to zh_cn lang file.
2. The forge-registered Milk fluid is not properly translated (affects the names of discrete fluid containers). This could be fixed, but it is likely a forge issue.

**Pull request merged**
