### PR TITLE
Fix barrel tooltip

### LINKED ISSUE #2575: Barrel recipe tooltip resets after world loading
This only occurs outside spawn chunks.

### PR DESCRIPTION
**Pull request by HermitOwO**
Fix #2575

### CODE REVIEW

**Comment by eerussianguy** [comment]
Please don't rename methods for no reason, that's a breaking change

**Comment by HermitOwO** [comment]
it's a method only used for tooltip
can leave an unused getRecipeTick() though

**Comment by eerussianguy** [comment]
We aren't the only ones that use TFC code, any number of addon and pack developers rely on it. We aren't gonna rename public methods for no reason, I don't care if nobody uses it.

**Comment by eerussianguy** [comment]
If you add a new method with a new function, sure, keep the new method, don't delete things.

**Pull request merged**
