### PR TITLE
Translation: 1.18.x Chinese family language (zh_CN, zh_HK, zh_TW)

### PR DESCRIPTION
**Pull request by recolic**
## If you are looking for Chinese Translation for 1.18.x

sadly 1.18.x branch cannot accept any further PR. You can download Chinese Translated mod pack at: <https://github.com/recolic/TerraFirmaCraft-ChineseLangEdition/releases>

----

This PR updates Chinese language files to include all latest mod content for 1.18.x branch. It also adds a note to tell future contributor to run `opencc` conversion & make sure all 3 jsons got updated together.

After my PR:

```
root@ffdac78ae3ad:/z# python3 resources/generate_book.py --translate zh_cn
Reading translation for language zh_cn to ./resources/lang/zh_cn.json
Writing book at zh_cn
Writing updated translation for language zh_cn: 997 / 1000 (99.70%)
root@ffdac78ae3ad:/z# python3 resources/generate_book.py --translate zh_tw
Reading translation for language zh_tw to ./resources/lang/zh_tw.json
Writing book at zh_tw
Writing updated translation for language zh_tw: 997 / 1000 (99.70%)
root@ffdac78ae3ad:/z# python3 resources/generate_book.py --translate zh_hk
Reading translation for language zh_hk to ./resources/lang/zh_hk.json
Writing book at zh_hk
Writing updated translation for language zh_hk: 997 / 1000 (99.70%)
```

Thanks for review!

### CODE REVIEW

**Comment by alcatrazEscapee** [comment]
We are not maintaining 1.18 anymore, please target this for the 1.20.x branch.

**Comment by recolic** [comment]
Hi.. I understand we are not adding new feature to 1.18.x, but many players are still enjoying this version so much. This patch will be helpful.

And because there would be no more update, this will be my final translation, will never invalidate, will works forever...

Could you reconsider this as a `bug fix` and just have it merged? I will also port it to 1.20.x to help more player.

Thanks for help!

**Comment by alcatrazEscapee** [comment]
No, when I said we are not maintaining 1.18 anymore, I mean we are not maintaining 1.18 anymore. Neither would we accept a PR to any older version.

**Comment by recolic** [comment]
sorry for being late...

**Pull request closed without merging**
