### PR TITLE
Add jade tooltip for barrel recipe time and charcoal forge remaining fuel time

### PR DESCRIPTION
**Pull request by HermitOwO**

### CODE REVIEW

**Comment by eerussianguy** [comment]
We've decided not to include burn ticks for jade tooltips as they are not synced regularly for every device

**Comment by HermitOwO** [comment]
I see, how about barrel recipe time?

**Comment by eerussianguy** [comment]
Seems fine to me.

**Comment by HermitOwO** [comment]
Got it updated

**Comment by eerussianguy** [comment]
BTW i'm changing it to Calendars.get(level) on my own commit as the sidedness of Jade is actually a little up in the air...

**Pull request merged**
