### PR TITLE
Add a Collapse Event

### PR DESCRIPTION
**Pull request by Notenoughmail**
Adds an event which provides the `centerPos`, `nextPositions`, `radiusSquared`, and level of a collapse

### CODE REVIEW

**Comment by pietro-lopes** [comment]
While we are at it, can I ask to add this to FakeCollapses too? maybe using same event and send a boolean if it is a fake or not

**Comment by Notenoughmail** [comment]
That can be done, but the radius of the fake collapses will have to be 0, as that only exists during a real collapse.

Otherwise, I could try to create a radius from the randx/y/z that are used to find unsupported blocks

**Comment by pietro-lopes** [comment]
I'm fine with having no radius, because if the dev needs he can inflate the radius for whatever reason
Does it give at least the center point?

**Comment by Notenoughmail** [comment]
Yes, the centerPos is available

**Comment by pietro-lopes** [comment]
Looking good to me 😀

**Review by eerussianguy — APPROVED** [review]

**Pull request merged**
