### PR TITLE
[Ready for review] Now forge can only be lit if requirements are met.

### PR DESCRIPTION
**Pull request by CtrlAltDavid01**
I noticed that charcoal pile only drops 1 charcoal if the block under it gets destroyed, should I drop its item LAYERS times, so the proper amount is dropped?

(Its my first ever interaction with java and minecraft modding, hopefully I don't mess up anything)

### CODE REVIEW

**Comment by CtrlAltDavid01** [comment]
I didn't see the issue you created I'll update accordingly

**Comment by CtrlAltDavid01** [comment]
And made charcoal piles drop the correct amount when the lock is broken below it.

**Comment by Bunsan** [comment]
The charcoal pile dropping all charcoal pieces when block below is broken makes it so player can just dig out bottom block to harvest the pile no matter how high it is. This is not behaviour we want. I don’t disagree only dropping one piece is mean, but this isn’t a good solution.

**Comment by CtrlAltDavid01** [comment]
I see the problem, should I undo it or something else?

**Comment by alcatrazEscapee** [comment]
@CtrlAltDavid01, look at the `removedByPlayer` and `onNeighourChange` methods in `BlockCharcoalPile` - it doesn't break normally. If you try and run this you'll end up having huge duplication bugs when you try and break charcoal

**Comment by CtrlAltDavid01** [comment]
I have tried every way I could think of and there is no dupe.

**Pull request closed without merging**
