### PR TITLE
Fixes issue #2216 for zh_tw, and add more translation for zh_cn & zh_tw

### LINKED ISSUE #2216: [2.1.17-beta] Error building entry tfc:mechanics/gems while opening in-game field guide
## Observed issue

If I open the in-game field guide, it shows an `Loading Error`. The error message says `Error building entry tfc:mechanics/gems, Error while loading entry tfc:mechanics/gems page 1, Malformed item ID`. 

The game is not crashed, but the book can not be read. 

This problem is observed in: 

|Mod Version|2.1.16|2.1.17|
|---|---|---|
|en_us|good|bad|
|zh_cn|good|bad|
|zh_tw|N/A|bad|

Screenshot: 

[Screenshot from 2022-11-02 15-32-25](https://user-images.githubusercontent.com/19610256/199615790-1aa07155-7f91-4b04-a5d8-a4a6af0dd381.png)

Log: 

<details>
  <summary>Click me</summary>

```
[15:30:52] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:30:53] [Render thread/INFO]: Preparing spawn area: 0%
[15:30:53] [Render thread/INFO]: Preparing spawn area: 0%
[15:30:53] [Render thread/INFO]: Preparing spawn area: 1%
[15:30:54] [Render thread/INFO]: Preparing spawn area: 18%
[15:30:54] [Server thread/INFO]: Successfully initialized permission handler forge:default_handler
[15:30:54] [Server thread/INFO]: Sending reload packet to clients
[15:30:54] [Server thread/INFO]: Changing view distance to 12, from 10
[15:30:54] [Server thread/INFO]: Changing simulation distance to 12, from 0
[15:30:54] [Render thread/INFO]: Time elapsed: 1883 ms
[15:30:55] [Netty Local Client IO #2/INFO]: Connected to a modded server.
[15:30:55] [Server thread/INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@2e0f440f
[15:30:55] [Server thread/INFO]: rrreco[local:E:c24c522a] logged in with entity id 1553 at (-7121.97256297548, 64.0, -4839.300000011921)
[15:30:55] [Server thread/INFO]: rrreco joined the game
[15:30:55] [Server thread/INFO]: Player Logged In - Checking for Calendar Updates.
[15:30:55] [Server thread/INFO]: Reverted doDaylightCycle to true as players are logged in.
[15:30:55] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggedInEvent
[15:30:55] [Render thread/INFO]: JEI StartEventObserver transitioning state from DISABLED to ENABLED
[15:30:55] [Render thread/INFO]: Ignored greenhouse(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored plantable(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored metal(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored fuel(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored fertilizer(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored item heat(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored food(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored item size(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored climate range(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored drinkable(s) sync from logical server
[15:30:55] [Render thread/INFO]: Ignored lamp_fuel(s) sync from logical server
[15:30:55] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.client.event.RecipesUpdatedEvent
[15:30:55] [Render thread/INFO]: Editing item stack sizes: found 5137 editable of 5649 total.
[15:30:55] [Render thread/INFO]: JEI StartEventObserver received class net.minecraftforge.event.TagsUpdatedEvent
[15:30:55] [Render thread/INFO]: JEI StartEventObserver transitioning state from ENABLED to JEI_STARTED
[15:30:55] [Render thread/INFO]: Starting JEI...
[15:30:55] [Render thread/INFO]: Registering item subtypes: jei:minecraft ...
[15:30:55] [Render thread/INFO]: Registering item subtypes: jei:minecraft took 18.30 μs
[15:30:55] [Render thread/INFO]: Registering item subtypes: tfc:jei ...
[15:30:55] [Render thread/INFO]: Registering item subtypes: tfc:jei took 3.090 μs
[15:30:55] [Render thread/INFO]: Registering item subtypes: firmalife:jei ...
[15:30:55] [Render thread/INFO]: Registering item subtypes: firmalife:jei took 3.219 μs
[15:30:55] [Render thread/INFO]: Registering item subtypes: curios:curios ...
[15:30:55] [Render thread/INFO]: Registering item subtypes: curios:curios took 3.290 μs
[15:30:55] [Render thread/INFO]: Registering item subtypes: patchouli:patchouli ...
[15:30:55] [Render thread/INFO]: Registering item subtypes: patchouli:patchouli took 6.720 μs
[15:30:55] [Render thread/INFO]: Registering item subtypes: jei:debug ...
[15:30:55] [Render thread/INFO]: Registering item subtypes: jei:debug took 3.090 μs
[15:30:55] [Render thread/INFO]: Registering item subtypes: jei:forge ...
[15:30:55] [Render thread/INFO]: Registering item subtypes: jei:forge took 3.110 μs
[15:30:55] [Render thread/INFO]: Registering item subtypes: jei:internal ...
[15:30:55] [Render thread/INFO]: Registering item subtypes: jei:internal took 3.150 μs
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: jei:minecraft ...
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: jei:minecraft took 3.440 μs
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: tfc:jei ...
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: tfc:jei took 3.090 μs
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: firmalife:jei ...
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: firmalife:jei took 3.090 μs
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: curios:curios ...
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: curios:curios took 3.310 μs
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: patchouli:patchouli ...
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: patchouli:patchouli took 3.240 μs
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: jei:debug ...
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: jei:debug took 9.269 μs
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: jei:forge ...
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: jei:forge took 3.250 μs
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: jei:internal ...
[15:30:55] [Render thread/INFO]: Registering fluid subtypes: jei:internal took 3.020 μs
[15:30:55] [Render thread/INFO]: Registering ingredients: jei:minecraft ...
[15:30:55] [Render thread/INFO]: Registering ingredients: jei:minecraft took 17.97 ms
[15:30:55] [Render thread/INFO]: Registering ingredients: tfc:jei ...
[15:30:55] [Render thread/INFO]: Registering ingredients: tfc:jei took 3.210 μs
[15:30:55] [Render thread/INFO]: Registering ingredients: firmalife:jei ...
[15:30:55] [Render thread/INFO]: Registering ingredients: firmalife:jei took 3.120 μs
[15:30:55] [Render thread/INFO]: Registering ingredients: curios:curios ...
[15:30:55] [Render thread/INFO]: Registering ingredients: curios:curios took 3.150 μs
[15:30:55] [Render thread/INFO]: Registering ingredients: patchouli:patchouli ...
[15:30:55] [Render thread/INFO]: Registering ingredients: patchouli:patchouli took 3.250 μs
[15:30:55] [Render thread/INFO]: Registering ingredients: jei:debug ...
[15:30:55] [Render thread/INFO]: Registering ingredients: jei:debug took 5.839 μs
[15:30:55] [Render thread/INFO]: Registering ingredients: jei:forge ...
[15:30:55] [Render thread/INFO]: Registering ingredients: jei:forge took 109.4 μs
[15:30:55] [Render thread/INFO]: Registering ingredients: jei:internal ...
[15:30:55] [Render thread/INFO]: Registering ingredients: jei:internal took 3.300 μs
[15:30:55] [Render thread/INFO]: Building ingredient list...
[15:30:55] [Render thread/INFO]: Building ingredient list took 1.331 ms
[15:30:55] [Render thread/INFO]: Building ingredient filter...
[15:30:55] [Render thread/INFO]: Adding 5973 ingredients
[15:30:55] [Render thread/INFO]: Added 5973 ingredients
[15:30:55] [Render thread/INFO]: Building ingredient filter took 129.0 ms
[15:30:55] [Render thread/INFO]: Building bookmarks...
[15:30:55] [Render thread/INFO]: Building bookmarks took 108.7 μs
[15:30:55] [Render thread/INFO]: Registering categories: jei:minecraft ...
[15:30:55] [Render thread/INFO]: Registering categories: jei:minecraft took 207.2 μs
[15:30:55] [Render thread/INFO]: Registering categories: tfc:jei ...
[15:30:55] [Render thread/INFO]: Registering categories: tfc:jei took 164.7 μs
[15:30:55] [Render thread/INFO]: Registering categories: firmalife:jei ...
[15:30:55] [Render thread/INFO]: Registering categories: firmalife:jei took 46.81 μs
[15:30:55] [Render thread/INFO]: Registering categories: curios:curios ...
[15:30:55] [Render thread/INFO]: Registering categories: curios:curios took 3.350 μs
[15:30:55] [Render thread/INFO]: Registering categories: patchouli:patchouli ...
[15:30:55] [Render thread/INFO]: Registering categories: patchouli:patchouli took 3.300 μs
[15:30:55] [Render thread/INFO]: Registering categories: jei:debug ...
[15:30:55] [Render thread/INFO]: Registering categories: jei:debug took 5.890 μs
[15:30:55] [Render thread/INFO]: Registering categories: jei:forge ...
[15:30:55] [Render thread/INFO]: Registering categories: jei:forge took 3.340 μs
[15:30:55] [Render thread/INFO]: Registering categories: jei:internal ...
[15:30:55] [Render thread/INFO]: Registering categories: jei:internal took 8.550 μs
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: jei:minecraft ...
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: jei:minecraft took 7.590 μs
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: tfc:jei ...
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: tfc:jei took 7.940 μs
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: firmalife:jei ...
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: firmalife:jei took 3.120 μs
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: curios:curios ...
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: curios:curios took 3.230 μs
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: patchouli:patchouli ...
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: patchouli:patchouli took 3.070 μs
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: jei:debug ...
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: jei:debug took 3.140 μs
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: jei:forge ...
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: jei:forge took 3.370 μs
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: jei:internal ...
[15:30:55] [Render thread/INFO]: Registering vanilla category extensions: jei:internal took 3.199 μs
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: jei:minecraft ...
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: jei:minecraft took 33.52 μs
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: tfc:jei ...
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: tfc:jei took 124.7 μs
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: firmalife:jei ...
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: firmalife:jei took 12.40 μs
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: curios:curios ...
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: curios:curios took 3.110 μs
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: patchouli:patchouli ...
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: patchouli:patchouli took 3.310 μs
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: jei:debug ...
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: jei:debug took 4.380 μs
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: jei:forge ...
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: jei:forge took 3.220 μs
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: jei:internal ...
[15:30:55] [Render thread/INFO]: Registering recipe catalysts: jei:internal took 4.530 μs
[15:30:55] [Render thread/INFO]: Registering advanced plugins: jei:minecraft ...
[15:30:55] [Render thread/INFO]: Registering advanced plugins: jei:minecraft took 3.680 μs
[15:30:55] [Render thread/INFO]: Registering advanced plugins: tfc:jei ...
[15:30:55] [Render thread/INFO]: Registering advanced plugins: tfc:jei took 3.560 μs
[15:30:55] [Render thread/INFO]: Registering advanced plugins: firmalife:jei ...
[15:30:55] [Render thread/INFO]: Registering advanced plugins: firmalife:jei took 3.280 μs
[15:30:55] [Render thread/INFO]: Registering advanced plugins: curios:curios ...
[15:30:55] [Render thread/INFO]: Registering advanced plugins: curios:curios took 3.260 μs
[15:30:55] [Render thread/INFO]: Registering advanced plugins: patchouli:patchouli ...
[15:30:55] [Render thread/INFO]: Registering advanced plugins: patchouli:patchouli took 3.170 μs
[15:30:55] [Render thread/INFO]: Registering advanced plugins: jei:debug ...
[15:30:55] [Render thread/INFO]: Registering advanced plugins: jei:debug took 3.050 μs
[15:30:55] [Render thread/INFO]: Registering advanced plugins: jei:forge ...
[15:30:55] [Render thread/INFO]: Registering advanced plugins: jei:forge took 3.250 μs
[15:30:55] [Render thread/INFO]: Registering advanced plugins: jei:internal ...
[15:30:55] [Render thread/INFO]: Registering advanced plugins: jei:internal took 3.180 μs
[15:30:55] [Render thread/INFO]: Building recipe registry...
[15:30:55] [Render thread/INFO]: Building recipe registry took 302.5 μs
[15:30:55] [Render thread/INFO]: Registering recipes: jei:minecraft ...
[15:30:55] [Render thread/INFO]: Registering recipes: jei:minecraft took 85.41 ms
[15:30:55] [Render thread/INFO]: Registering recipes: tfc:jei ...
[15:30:56] [Render thread/INFO]: Registering recipes: tfc:jei took 46.65 ms
[15:30:56] [Render thread/INFO]: Registering recipes: firmalife:jei ...
[15:30:56] [Render thread/INFO]: Registering recipes: firmalife:jei took 951.7 μs
[15:30:56] [Render thread/INFO]: Registering recipes: curios:curios ...
[15:30:56] [Render thread/INFO]: Registering recipes: curios:curios took 3.120 μs
[15:30:56] [Render thread/INFO]: Registering recipes: patchouli:patchouli ...
[15:30:56] [Render thread/INFO]: Registering recipes: patchouli:patchouli took 3.160 μs
[15:30:56] [Render thread/INFO]: Registering recipes: jei:debug ...
[15:30:56] [Render thread/INFO]: Registering recipes: jei:debug took 6.560 μs
[15:30:56] [Render thread/INFO]: Registering recipes: jei:forge ...
[15:30:56] [Render thread/INFO]: Registering recipes: jei:forge took 16.23 ms
[15:30:56] [Render thread/INFO]: Registering recipes: jei:internal ...
[15:30:56] [Render thread/INFO]: Registering recipes: jei:internal took 7.340 μs
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: jei:minecraft ...
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: jei:minecraft took 32.82 μs
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: tfc:jei ...
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: tfc:jei took 3.000 μs
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: firmalife:jei ...
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: firmalife:jei took 3.300 μs
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: curios:curios ...
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: curios:curios took 3.049 μs
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: patchouli:patchouli ...
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: patchouli:patchouli took 3.170 μs
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: jei:debug ...
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: jei:debug took 2.980 μs
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: jei:forge ...
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: jei:forge took 3.350 μs
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: jei:internal ...
[15:30:56] [Render thread/INFO]: Registering recipes transfer handlers: jei:internal took 2.970 μs
[15:30:56] [Render thread/INFO]: Building runtime...
[15:30:56] [Render thread/INFO]: Registering gui handlers: jei:minecraft ...
[15:30:56] [Render thread/INFO]: Registering gui handlers: jei:minecraft took 54.14 μs
[15:30:56] [Render thread/INFO]: Registering gui handlers: tfc:jei ...
[15:30:56] [Render thread/INFO]: Registering gui handlers: tfc:jei took 2.170 μs
[15:30:56] [Render thread/INFO]: Registering gui handlers: firmalife:jei ...
[15:30:56] [Render thread/INFO]: Registering gui handlers: firmalife:jei took 1.750 μs
[15:30:56] [Render thread/INFO]: Registering gui handlers: curios:curios ...
[15:30:56] [Render thread/INFO]: Registering gui handlers: curios:curios took 10.67 μs
[15:30:56] [Render thread/INFO]: Registering gui handlers: patchouli:patchouli ...
[15:30:56] [Render thread/INFO]: Registering gui handlers: patchouli:patchouli took 7.180 μs
[15:30:56] [Render thread/INFO]: Registering gui handlers: jei:debug ...
[15:30:56] [Render thread/INFO]: Registering gui handlers: jei:debug took 9.639 μs
[15:30:56] [Render thread/INFO]: Registering gui handlers: jei:forge ...
[15:30:56] [Render thread/INFO]: Registering gui handlers: jei:forge took 2.990 μs
[15:30:56] [Render thread/INFO]: Registering gui handlers: jei:internal ...
[15:30:56] [Render thread/INFO]: Registering gui handlers: jei:internal took 10.47 μs
[15:30:56] [Render thread/INFO]: Building runtime took 759.8 μs
[15:30:56] [Render thread/INFO]: Sending Runtime: jei:minecraft ...
[15:30:56] [Render thread/INFO]: Sending Runtime: jei:minecraft took 25.31 μs
[15:30:56] [Render thread/INFO]: Sending Runtime: tfc:jei ...
[15:30:56] [Render thread/INFO]: Sending Runtime: tfc:jei took 2.680 μs
[15:30:56] [Render thread/INFO]: Sending Runtime: firmalife:jei ...
[15:30:56] [Render thread/INFO]: Sending Runtime: firmalife:jei took 2.540 μs
[15:30:56] [Render thread/INFO]: Sending Runtime: curios:curios ...
[15:30:56] [Render thread/INFO]: Sending Runtime: curios:curios took 2.380 μs
[15:30:56] [Render thread/INFO]: Sending Runtime: patchouli:patchouli ...
[15:30:56] [Render thread/INFO]: Sending Runtime: patchouli:patchouli took 2.600 μs
[15:30:56] [Render thread/INFO]: Sending Runtime: jei:debug ...
[15:30:56] [Render thread/INFO]: Sending Runtime: jei:debug took 3.520 μs
[15:30:56] [Render thread/INFO]: Sending Runtime: jei:forge ...
[15:30:56] [Render thread/INFO]: Sending Runtime: jei:forge took 2.590 μs
[15:30:56] [Render thread/INFO]: Sending Runtime: jei:internal ...
[15:30:56] [Render thread/INFO]: Sending Runtime: jei:internal took 2.400 μs
[15:30:56] [Render thread/INFO]: Starting JEI took 317.8 ms
[15:30:56] [Render thread/INFO]: Loaded 49 advancements
[15:30:56] [Render thread/ERROR]: Error compiling book tfc:field_guide, using empty contents
java.lang.RuntimeException: Error building entry tfc:mechanics/gems
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:98) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
	at vazkii.patchouli.client.book.BookContentsBuilder.build(BookContentsBuilder.java:94) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.Book.reloadContents(Book.java:225) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.common.book.BookRegistry.reloadContents(BookRegistry.java:128) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.ClientBookRegistry.reload(ClientBookRegistry.java:63) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.client.base.ClientAdvancements.onClientPacket(ClientAdvancements.java:34) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at net.minecraft.client.multiplayer.ClientAdvancements.handler$zci000$patchouli_onSync(ClientAdvancements.java:1017) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.client.multiplayer.ClientAdvancements.m_104399_(ClientAdvancements.java:57) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.client.multiplayer.ClientPacketListener.m_5498_(ClientPacketListener.java:1135) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:51) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.network.protocol.game.ClientboundUpdateAdvancementsPacket.m_5797_(ClientboundUpdateAdvancementsPacket.java:16) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1015) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:665) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%2359!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.84.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.RuntimeException: Error while loading entry tfc:mechanics/gems page 1
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:250) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	... 32 more
Caused by: java.lang.RuntimeException: Malformed item ID 
	at vazkii.patchouli.common.util.ItemStackUtil.parseItemStackString(ItemStackUtil.java:78) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackFromString(ItemStackUtil.java:114) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.common.util.ItemStackUtil.loadStackListFromString(ItemStackUtil.java:147) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.common.util.ItemStackUtil.loadIngredientFromString(ItemStackUtil.java:128) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.template.variable.IngredientVariableSerializer.fromJson(IngredientVariableSerializer.java:13) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.template.variable.IngredientVariableSerializer.fromJson(IngredientVariableSerializer.java:10) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.template.variable.Variable.as(Variable.java:31) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.page.PageSpotlight.build(PageSpotlight.java:29) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookEntry.build(BookEntry.java:247) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	at vazkii.patchouli.client.book.BookContentsBuilder.lambda$build$2(BookContentsBuilder.java:96) ~[Patchouli-1.18.2-71.1.jar%2356!/:1.18.2-71.1]
	... 32 more
```

</details>

## System Info

Mod list: 

```
Patchouli-1.18.2-71.1.jar [from CurseForge]
TerraFirmaCraft-Forge-1.18.2-2.1.17-beta.jar [from GitHub]
```

Environment: 

```
Java 17.0.5 on Linux (OpenJDK)
Minecraft 1.18.2 with Forge 40.1.84
```

### PR DESCRIPTION
**Pull request by recolic**
The previous commits fixed #2216 for en_us, ko_kr, zh_cn, but did not fix zh_tw. This PR fixes it. 
Also add more translation for zh_cn & zh_tw.

### CODE REVIEW

**Comment by recolic** [comment]
Please do a `squash and merge`. There are some junk commits for my testing, and I don't want them to pollute the commit history. 
Thanks.

**Comment by eerussianguy** [comment]
this has merge conflicts now given alcatraz's bugfix

**Comment by recolic** [comment]
DO NOT MERGE please. There is more translate to catch up

**Comment by recolic** [comment]
Conflict resolved. Good for merge.

**Pull request merged**
