### PR TITLE
Add ru_ru book localization

### PR DESCRIPTION
**Pull request by NaoCraftLab**
Hello! I have completed a full translation of the book Patchouli into Russian and intend to keep it up to date.

### CODE REVIEW

**Comment by ItzShiney** [comment]
just a couple of notes/suggestions
* a typo in `"Wild Wheat": "Дикий Пшеница",`
* "яблоневое дерево" isn't really a thing, is it? i think it should be `Красная яблоня` or maybe, more accurate, `Дерево красных яблок`
* `"The monthly stages of a XXX.": "Ежемесячные стадии XXX.",` — `Стадии XXX по месяцам`?
* the `They are nocturnal` → `Они ночные` lost some context. could be `Ведут ночной образ жизни`
* `"Prey": "Жертвы",` — i guess `Жертва` is also used in this context, but i think i personally would go with `Добыча`. may be a regional thing, idk
* `$(l:the_world/climate#rainfall)осадках$() между XXX и YYYмм.",` — `от XXX до YYYмм`
* `появляется в любой реке или озере` — `в реках и озёрах`. and maybe `появляется` (`spawn`) → `обитает`?
* `Интерфейс Кремнения` — not `кремнения` (a non-existent word) but `высекания`?

**Comment by NaoCraftLab** [comment]
@ItzShiney 

> * `"Prey": "Жертвы",` — i guess `Жертва` is also used in this context, but i think i personally would go with `Добыча`. may be a regional thing, idk

The antonym of "хищник" is "жертва". The word "Добыча" also fits, but there are issues with phrases like "Добычи боятся игроков". "Жертвы боятся игроков" sounds much better, although it's still not perfect.

**Comment by DarthSidiousPalpatine** [comment]
> @ItzShiney
> 
> > * `"Prey": "Жертвы",` — i guess `Жертва` is also used in this context, but i think i personally would go with `Добыча`. may be a regional thing, idk
> 
> The antonym of "хищник" is "жертва". The word "Добыча" also fits, but there are issues with phrases like "Добычи боятся игроков". "Жертвы боятся игроков" sounds much better, although it's still not perfect.

We have a word Дичь. But in some cases Добыча is much better, but... "наземная добыча" is sooo weird. If you know russian and you are trying to translate something - please, spell it out loud and just hear yourself. Is it comfortable to read/spell or not.

upd. Its soo weird in details. I was hoping that someone'll make a full translation, so i dont have to make one for my friends, as i did for tfc+, but... Fine, I'll do it myself...

**Comment by NaoCraftLab** [comment]
@DarthSidiousPalpatine

> upd. Its soo weird in details. I was hoping that someone'll make a full translation, so i dont have to make one for my friends, as i did for tfc+, but... Fine, I'll do it myself...

That's exactly how I started making this translation. I wanted to translate TFC2 for myself. But then I decided it would be better to do it for the whole community, since no one had done it before me. My English is far from perfect (otherwise, why would I need a translation?).

If you don't mind spending time on a full translation of TFC3, maybe it would be better if you could do a full review of my translation and make corrections in the PR or write comments? This way, everyone will get a good translation, not just your friends.

**Pull request merged**
